[package]
name = "bench-loop"
version = "0.1.0"
authors = ["Caio O Campos <caio.campos1204@gmail.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
